name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install  # Installa le dipendenze (compreso Jest)

      - name: Fix permissions for jest binary
        run: chmod +x ./node_modules/.bin/jest  # Forza i permessi corretti sul binario di Jest

      - name: Run tests with coverage
        run: npm test -- --coverage  # Esegui i test con Jest

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/ 

